# cloudbuild.yaml
steps:
- name: 'docker.io/library/python:3.8'
  id: Test
  entrypoint: /bin/sh
  args: [-c, 'python -m unittest dags/tests/test_python_scripts.py']
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: Deploy To Test
  entrypoint: bash
  args: [ '-c', 'gsutil -m rsync -d -r ./dags gs://${_COMPOSER_BUCKET}/data/test']
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: Check DAG Parsing Errors
  entrypoint: bash
  args: [-c, 'python3 dags/tests/dag_parsing_test.py']
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: Deploy DAGs
  entrypoint: bash
  args: [ '-c', 'gsutil -m rsync -d -r ./dags gs://${_COMPOSER_BUCKET}/dags']
substitutions:
    _COMPOSER_BUCKET: us-central1-my-environment-53f4281a-bucket
    _COMPOSER_ENVIRONMENT: my-environment
    _COMPOSER_REGION: us-central1