# cloudbuild.yaml
steps:
- name: 'docker.io/library/python:3.8'
  id: Test
  entrypoint: /bin/sh
  args: [-c, 'python -m unittest dags/tests/test_python_scripts.py']
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: Deploy To Test
  entrypoint: bash
  args: [ '-c', 'gsutil -m rsync -d -r ./dags gs://${_COMPOSER_BUCKET}/data/test']
#- name: gcr.io/cloud-builders/gcloud
#  id: Test DAGs
#  entrypoint: gcloud
#  args: ['composer environments', 'run', 'my-environment', '--location', 'us-central1', 'dags list', '--', '--subdir', '/home/airflow/gcs/data/test']
#- name: gcr.io/google.com/cloudsdktool/cloud-sdk
#  id: Check DAG Parsing Errors
#  entrypoint: bash
#  args: [ '-c', 'gcloud composer environments run my-environment --location us-central1 dags list-import-errors -- --subdir /home/airflow/gcs/data/test/']
#- name: gcr.io/cloud-builders/gcloud
#  id: Check DAG Parsing Errors
#  entrypoint: bash
#  args: ['dags/tests/dag_parsing_test.sh', '${_COMPOSER_ENVIRONMENT}', '${_COMPOSER_REGION}']
#- name: gcr.io/google.com/cloudsdktool/cloud-sdk
#  id: Check DAG Parsing Errors
#  entrypoint: bash
#  args: [-c, 'python3 dags/tests/dag_parsing_test.py']
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: List Dags
  entrypoint: bash
  args:
  - '-c'
  - |-
    gcloud composer environments run my-environment --quiet --location us-central1 dags list-import-errors -- --subdir /home/airflow/gcs/data/test/ > output.txt
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: Check DAG Parsing Errors
  entrypoint: bash
  args:
  - '-c'
  - |-
    while read line; do
      echo $line
      if grep -q "Error" <<< "$line"; then
          echo $line
      fi
    done < output.txt
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: Deploy DAGs
  entrypoint: bash
  args: [ '-c', 'gsutil -m rsync -d -r ./dags gs://${_COMPOSER_BUCKET}/dags']
substitutions:
    _COMPOSER_BUCKET: us-central1-my-environment-ffd19eba-bucket
    _COMPOSER_ENVIRONMENT: my-environment
    _COMPOSER_REGION: us-central1